image: Ubuntu

stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - java -jar ./artifacts/app-ibank.jar -P:profile=test &
  - chmod +x gradlew

build_script:
  - ps:  chmod +x gradlew
  - ps: ./gradlew test --info "-Dselenide.headless=true"